apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-manager
  namespace: praveen-ns
rules:
- apiGroups: [""]
  resources: ["nodes","namespaces","pods"]
  verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]