apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devgroup-role 
  namespace: praveen-ns
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]